### ISSUE TITLE
bunch of errors

### ISSUE THREAD

**Issue by ngmisl** [ali-furkan/minesweeper-v#5]
v run .

./app.v:106:9: warning: method `gg.Context.draw_rounded_rect` has been deprecated; use draw_rounded_rect_filled()
  104 | 
  105 |     // Draw Board
  106 |     app.gg.draw_rounded_rect(xstart - tile_size / 2, ystart - tile_size / 2, bsize, bsize,
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  107 |         bsize / 24, app.ui.theme.board_color)
  108 |
./app.v:127:11: warning: method `gg.Context.draw_rounded_rect` has been deprecated; use draw_rounded_rect_filled()
  125 |             t_size := tile_size - border_size
  126 | 
  127 |             app.gg.draw_rounded_rect(tile_x_start, tile_y_start, t_size, t_size, tile_size / 8,
      |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  128 |                 color)
  129 |
./app.v:169:21: warning: function `math.mathutil.min` has been deprecated since 2022-01-19, it will be an error after 2022-07-18; use math.min instead
  167 |     w := window_size.width
  168 |     h := window_size.height
  169 |     min_edge := f32(mu.min(w, h))
      |                        ~~~~~~~~~
  170 | 
  171 |     app.ui.window_width = w
./board.v:36:18: error: rand.intn() returns an option, so it should have either an `or {}` block, or `?` at the end
   34 |     mut i := 0
   35 |     for i < num_mines {
   36 |         mine_x := rand.intn(cells - 1)
      |                        ~~~~~~~~~~~~~~~
   37 |         mine_y := rand.intn(cells - 1)
   38 |
./board.v:37:18: error: rand.intn() returns an option, so it should have either an `or {}` block, or `?` at the end
   35 |     for i < num_mines {
   36 |         mine_x := rand.intn(cells - 1)
   37 |         mine_y := rand.intn(cells - 1)
      |                        ~~~~~~~~~~~~~~~
   38 | 
   39 |         if board.cells[mine_y][mine_x] == -1 {

**Comment by ali-furkan** [comment]
I've not used vlang a long time. I've seen v gets lots of update. These things are warns, it's not occur error but i need to fix it as the current v version. Thx for issue

**Comment by ali-furkan** [comment]
Also if you want to add new feat or fix the bug, you dont hesitate to send pr.
